export const LoginLang = {
    signin: 'Sign In',
    emailAddressPH: 'Email Address or Username',
    password: 'Password',
    continue: 'C O N T I N U E',
    connectWithSocialMedia: 'or Connect with Social Media',
    signInGoogle: 'Sign In With Google',
    dontHaveAccount: 'Don’t have an account?',
    signup: 'Sign up',
    incorrectPassword: 'Your password is incorrect',
    incorrectUsername: 'Your username is incorrect',
    welcomeBack: 'Welcome Back',
    welcomeBackText: 'Sign in to continue access pages',
    incorrectData: 'Your email address or password is incorrect',
};
