export const forgetLang = {
    forget: 'Forget Password',
    emailAddressPH: 'Email Address',
    password: 'Password',
    continue: 'C O N T I N U E',
    connectWithSocialMedia: 'or Connect with Social Media',
    signInGoogle: 'Sign In With Google',
    dontHaveAccount: 'Don’t have an account?',
    signup: 'Sign up',
    incorrectPassword: 'Your password is not in the correct format ',
    incorrectUsername: 'Your username or email is not in the correct format',
    welcomeBack: 'Welcome Back',
    welcomeBackText: 'Sign in to continue access pages',
    incorrectData: 'Your email address or password is incorrect',
    forgetpass:"Recovery password",
    emailSent: 'Email confirmation send',
    activeEmailText: 'To continue please click on a link that sent it to your email',
};
