export const setnewpassLang = {
    setnewpassword: 'New Password',
    emailAddressPH: 'Email Address or Username',
    password: 'Password',
    continue: 'C O N T I N U E',
    connectWithSocialMedia: 'or Connect with Social Media',
    signInGoogle: 'Sign In With Google',
    dontHaveAccount: 'Don’t have an account?',
    signup: 'Sign up',
    incorrectPassword: 'Your password is not in the correct format ',
    incorrectUsername: 'Your username or email is not in the correct format',
    welcomeBack: 'Welcome Back',
    welcomeBackText: 'Sign in to continue access pages',
    incorrectData: 'Your email address or password is incorrect',
    forgetpass: 'Recovery password',
    atLeast8Char: 'at least 8 characters',
    combineUpAndLow: 'combination of upper and lower case characters',
    moreDigit: 'one or more digits',
};
