export const SignupLang = {
    welcomeBack: 'Welcome Back',
    welcomeBackText: 'Sign up to continue access pages',
    incorrectUsername: 'Your username is not in a correct format',
    incorrectEmail: 'Your email address is not in a correct format',
    incorrectPassword: 'Your password is not secure',
    incorrectConfirmPassword: 'Your passwords is not same',
    signup: 'Sign Up',
    username: 'Username',
    email: 'Email Address',
    password: 'Password',
    atLeast8Char: 'at least 8 characters',
    combineUpAndLow: 'combination of upper and lower case characters',
    moreDigit: 'one or more digits',
    confirmPassword: 'Confirm password',
    continue: 'C O N T I N U E',
    connectWithSocialMedia: 'or Connect with Social Media',
    signInGoogle: 'Sign In With Google',
    haveAccount: 'have an account?',
    signin: 'Sign In',
    emailSent: 'Email confirmation send',
    activeEmailText: 'To continue please click on a link that sent it to your email',
};
