export const CreateGroupModalLang = {
    title: 'Create your Group',
    descriptionHeader: 'Give your new Group a personality with a name and image.\n' + 'You can always change it later.',
    upload: 'Upload',
    groupName: 'Group Name',
    groupId: 'Group ID',
    description: 'Description',
    privacyTitle: 'Group Privacy',
    private: 'Private',
    public: 'Public',
    semiPrivate: 'Semi-Private',
    friendTitle: 'Your Friends',
    search: 'Search your friends account…',
    owner: 'Owner',
    viewer: 'Viewer',
    controller: 'Controller',
    publicDescription: 'Anyone can join the group',
    semiPrivateDescription: 'For joining the group accepting a request is needed',
    privateDescription: 'Only admin can add the member',
};
